name: population_var_calling
channels:
  - defaults
  - bioconda
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - _r-mutex=1.0.1
  - adwaita-icon-theme=49.0
  - aioeasywebdav=2.4.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.0
  - aiosignal=1.4.0
  - alsa-lib=1.2.14
  - amply=0.1.6
  - anndata=0.11.4
  - annotated-types=0.7.0
  - aom=3.9.1
  - appdirs=1.4.4
  - argcomplete=3.6.3
  - array-api-compat=1.12.0
  - async-timeout=5.0.1
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - attrs=25.4.0
  - bcftools=1.22
  - bcrypt=5.0.0
  - bedtools=2.31.1
  - binutils_impl_linux-64=2.44
  - binutils_linux-64=2.44
  - bioconductor-biobase=2.66.0
  - bioconductor-biocgenerics=0.52.0
  - bioconductor-biocio=1.16.0
  - bioconductor-biocparallel=1.40.0
  - bioconductor-biostrings=2.74.0
  - bioconductor-data-packages=20250625
  - bioconductor-delayedarray=0.32.0
  - bioconductor-genomeinfodb=1.42.0
  - bioconductor-genomeinfodbdata=1.2.13
  - bioconductor-genomicalignments=1.42.0
  - bioconductor-genomicranges=1.58.0
  - bioconductor-iranges=2.40.0
  - bioconductor-matrixgenerics=1.18.0
  - bioconductor-noiseq=2.50.0
  - bioconductor-rhtslib=3.2.0
  - bioconductor-rsamtools=2.22.0
  - bioconductor-rtracklayer=1.66.0
  - bioconductor-s4arrays=1.6.0
  - bioconductor-s4vectors=0.44.0
  - bioconductor-sparsearray=1.6.0
  - bioconductor-summarizedexperiment=1.36.0
  - bioconductor-ucsc.utils=1.2.0
  - bioconductor-xvector=0.46.0
  - bioconductor-zlibbioc=1.52.0
  - blosc=1.21.6
  - boto3=1.40.59
  - botocore=1.40.59
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bwa-mem2=2.3
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.15.2
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=6.2.1
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.0
  - coin-or-cbc=2.10.12
  - coin-or-cgl=0.60.9
  - coin-or-clp=1.17.10
  - coin-or-osi=0.108.11
  - coin-or-utils=2.11.12
  - coincbc=2.10.12
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - colormath=3.0.0
  - configargparse=1.7.1
  - connection_pool=0.0.3
  - contourpy=1.3.2
  - coreutils=8.25
  - cpython=3.10.19
  - cryptography=46.0.3
  - curl=8.16.0
  - cycler=0.12.1
  - datrie=0.8.3
  - dav1d=1.2.1
  - dbus=1.16.2
  - defusedxml=0.7.1
  - docutils=0.22.2
  - dpath=2.2.0
  - dropbox=12.0.2
  - eido=0.2.4
  - epoxy=1.5.10
  - exceptiongroup=1.3.0
  - expat=2.7.1
  - fastahack=2016.07.2
  - fastp=1.0.1
  - fastqc=0.12.1
  - fftw=3.3.10
  - filechunkio=1.8
  - filelock=3.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freebayes=1.3.9
  - freetype=2.14.1
  - fribidi=1.0.16
  - frozenlist=1.7.0
  - ftputil=5.1.0
  - gcc_impl_linux-64=15.2.0
  - gcc_linux-64=15.2.0
  - gdk-pixbuf=2.44.4
  - gfortran_impl_linux-64=15.2.0
  - ghostscript=9.18
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.45
  - glib-tools=2.86.0
  - google-api-core=2.25.2
  - google-api-python-client=2.185.0
  - google-auth=2.41.1
  - google-auth-httplib2=0.2.0
  - google-cloud-core=2.4.3
  - google-cloud-storage=3.4.1
  - google-crc32c=1.7.1
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.70.0
  - graphite2=1.3.14
  - graphviz=13.1.2
  - gsl=2.7
  - gtk3=3.24.43
  - gts=0.7.6
  - gxx_impl_linux-64=15.2.0
  - gxx_linux-64=15.2.0
  - gzip=1.14
  - h2=4.3.0
  - h5py=3.13.0
  - harfbuzz=12.1.0
  - hdf5=1.14.3
  - hicolor-icon-theme=0.17
  - hpack=4.1.0
  - htslib=1.22.1
  - httplib2=0.31.0
  - humanfriendly=10.0
  - humanize=4.14.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - imagemagick=7.1.2_7
  - importlib-metadata=8.7.0
  - importlib_metadata=8.7.0
  - iniconfig=2.3.0
  - invoke=2.2.1
  - isa-l=2.31.1
  - jbig=2.1
  - jinja2=3.1.6
  - jmespath=1.0.1
  - joblib=1.5.2
  - jq=1.5
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jupyter_core=5.9.1
  - kaleido-core=0.2.1
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - legacy-api-wrap=1.4.1
  - lerc=4.0.0
  - libabseil=20250814.1
  - libaec=1.1.4
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.16.0
  - libde265=1.0.15
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libegl-devel=1.7.0
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=15.2.0
  - libgcc-ng=15.2.0
  - libgd=2.3.3
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libgl-devel=1.7.0
  - libglib=2.86.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libglx-devel=1.7.0
  - libgomp=15.2.0
  - libheif=1.19.7
  - libhwloc=2.12.1
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libpciaccess=0.18
  - libpng=1.6.50
  - librsvg=2.60.0
  - libsanitizer=15.2.0
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libunistring=0.9.10
  - libuuid=2.41.2
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.12.2
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxml2-devel=2.15.1
  - libzlib=1.3.1
  - llvmlite=0.45.1
  - logmuse=0.2.8
  - lz4-c=1.10.0
  - make=4.4.1
  - markdown=3.9
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - mathjax=2.7.7
  - matplotlib-base=3.10.7
  - mdurl=0.1.2
  - multidict=6.6.3
  - multiqc=1.31
  - munkres=1.0.7
  - narwhals=2.9.0
  - natsort=8.4.0
  - nbformat=5.10.4
  - ncbi-datasets-cli=18.9.0
  - ncurses=6.5
  - networkx=3.4.2
  - nlopt=2.10.0
  - nomkl=1.0
  - nspr=4.37
  - nss=3.117
  - numba=0.62.1
  - numexpr=2.14.1
  - numpy=2.2.6
  - oauth2client=4.1.3
  - openjdk=24.0.2
  - openjpeg=2.5.4
  - openssl=3.5.4
  - packaging=25.0
  - pandas=2.3.3
  - pango=1.56.4
  - parallel=20160622
  - paramiko=4.0.0
  - patsy=1.0.2
  - pcre2=10.46
  - pephubclient=0.4.4
  - peppy=0.40.8
  - perl=5.32.1
  - perl-threaded=5.32.1
  - pigz=2.8
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - pkg-config=0.29.2
  - plac=1.4.5
  - platformdirs=4.5.0
  - plink=1.90b7.7
  - plotly=6.3.1
  - pluggy=1.6.0
  - ply=3.11
  - polars=1.34.0
  - polars-lts-cpu=1.34.0.deprecated
  - polars-runtime-32=1.34.0
  - polars-runtime-compat=1.34.0
  - prettytable=3.16.0
  - propcache=0.3.1
  - proto-plus=1.26.1
  - protobuf=6.32.1
  - psutil=7.1.0
  - pthread-stubs=0.4
  - pulp=2.7.0
  - py-cpuinfo=9.0.0
  - pyaml-env=1.2.2
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycparser=2.22
  - pydantic=2.12.3
  - pydantic-core=2.41.4
  - pygments=2.19.2
  - pynacl=1.6.0
  - pynndescent=0.5.13
  - pyopenssl=25.3.0
  - pyparsing=3.2.5
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytables=3.10.1
  - pytest=8.4.2
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.1
  - python-fastjsonschema=2.21.2
  - python-gil=3.10.19
  - python-irodsclient=3.1.1
  - python-kaleido=0.2.1
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pyu2f=0.1.5
  - pyvcf=0.6.8
  - pyyaml=6.0.3
  - qhull=2020.2
  - qualimap=2.3
  - r-abind=1.4_8
  - r-askpass=1.2.1
  - r-backports=1.5.0
  - r-base=4.4.3
  - r-bh=1.87.0_1
  - r-bitops=1.0_9
  - r-boot=1.3_32
  - r-broom=1.0.10
  - r-car=3.1_3
  - r-cardata=3.0_5
  - r-caret=6.0_94
  - r-class=7.3_23
  - r-cli=3.6.5
  - r-clock=0.7.3
  - r-codetools=0.2_20
  - r-colorspace=2.1_2
  - r-conquer=1.3.3
  - r-corrplot=0.95
  - r-cowplot=1.2.0
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-curl=7.0.0
  - r-data.table=1.17.8
  - r-deriv=4.2.0
  - r-diagram=1.6.5
  - r-digest=0.6.37
  - r-doby=4.7.0
  - r-dplyr=1.1.4
  - r-e1071=1.7_16
  - r-ellipsis=0.3.2
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-foreach=1.5.2
  - r-formatr=1.14
  - r-formula=1.2_5
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-future=1.67.0
  - r-future.apply=1.20.0
  - r-gbrd=0.4.12
  - r-generics=0.1.4
  - r-getopt=1.20.4
  - r-ggplot2=4.0.0
  - r-ggpubr=0.6.2
  - r-ggrepel=0.9.6
  - r-ggsci=4.1.0
  - r-ggsignif=0.6.4
  - r-globals=0.18.0
  - r-glue=1.8.0
  - r-gower=1.0.1
  - r-gridextra=2.3
  - r-gtable=0.3.6
  - r-hardhat=1.4.2
  - r-httr=1.4.7
  - r-ipred=0.9_15
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jsonlite=2.0.0
  - r-kernsmooth=2.23_26
  - r-labeling=0.4.3
  - r-lambda.r=1.2.4
  - r-lattice=0.22_7
  - r-lava=1.8.1
  - r-lifecycle=1.0.4
  - r-listenv=0.9.1
  - r-lme4=1.1_37
  - r-lubridate=1.9.4
  - r-magrittr=2.0.4
  - r-mass=7.3_65
  - r-matrix=1.7_4
  - r-matrixmodels=0.5_4
  - r-matrixstats=1.5.0
  - r-mgcv=1.9_3
  - r-microbenchmark=1.5.0
  - r-mime=0.13
  - r-minqa=1.2.8
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.11
  - r-munsell=0.5.1
  - r-nlme=3.1_168
  - r-nloptr=2.2.1
  - r-nnet=7.3_20
  - r-numderiv=2016.8_1.1
  - r-openssl=2.3.4
  - r-optparse=1.7.5
  - r-parallelly=1.45.1
  - r-pbkrtest=0.5.5
  - r-pheatmap=1.0.13
  - r-pillar=1.11.1
  - r-pkgconfig=2.0.3
  - r-plyr=1.8.9
  - r-polynom=1.4_1
  - r-proc=1.19.0.1
  - r-prodlim=2025.04.28
  - r-progressr=0.17.0
  - r-proxy=0.4_27
  - r-purrr=1.1.0
  - r-quantreg=6.1
  - r-r6=2.6.1
  - r-rbibutils=2.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.1.0
  - r-rcpparmadillo=15.0.2_2
  - r-rcppeigen=0.3.4.0.2
  - r-rcurl=1.98_1.17
  - r-rdpack=2.6.4
  - r-recipes=1.3.1
  - r-reformulas=0.4.1
  - r-reshape2=1.4.4
  - r-restfulr=0.0.16
  - r-rjson=0.2.23
  - r-rlang=1.1.6
  - r-rpart=4.1.24
  - r-rstatix=0.7.3
  - r-s7=0.2.0
  - r-scales=1.4.0
  - r-shape=1.4.6.1
  - r-snow=0.4_4
  - r-sparsem=1.84_2
  - r-sparsevctrs=0.3.4
  - r-squarem=2021.1
  - r-stringi=1.8.7
  - r-stringr=1.5.2
  - r-survival=3.8_3
  - r-sys=3.4.3
  - r-tibble=3.3.0
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-timechange=0.3.0
  - r-timedate=4051.111
  - r-tzdb=0.5.0
  - r-utf8=1.2.6
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-withr=3.0.2
  - r-xml=3.99_0.17
  - r-xml2=1.4.0
  - r-yaml=2.3.10
  - rav1e=0.7.1
  - readline=8.2
  - referencing=0.37.0
  - regex=2025.10.23
  - requests=2.32.5
  - reretry=0.11.8
  - rich=14.2.0
  - rich-click=1.9.4
  - rpds-py=0.28.0
  - rsa=4.9.1
  - s3transfer=0.14.0
  - samblaster=0.1.26
  - samtools=1.22.1
  - scanpy=1.7.2
  - scikit-learn=1.7.2
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - sed=4.9
  - setuptools=80.9.0
  - setuptools-scm=9.2.2
  - setuptools_scm=9.2.2
  - shellingham=1.5.4
  - sinfo=0.3.1
  - six=1.17.0
  - slacker=0.14.0
  - smart_open=7.4.1
  - smmap=5.0.2
  - snakemake=7.32.4
  - snakemake-minimal=7.32.4
  - snappy=1.2.2
  - spectra=0.0.11
  - sqlite=3.50.4
  - statsmodels=0.14.5
  - stdlib-list=0.12.0
  - stone=3.3.2
  - stopit=1.1.2
  - svt-av1=3.1.2
  - sysroot_linux-64=2.34
  - tabixpp=1.1.2
  - tabulate=0.9.0
  - tbb=2022.2.0
  - threadpoolctl=3.6.0
  - throttler=1.2.2
  - tiktoken=0.12.0
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.3.0
  - tomlkit=0.13.3
  - toposort=1.10
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typeguard=4.4.4
  - typer=0.20.0
  - typer-slim=0.20.0
  - typer-slim-standard=0.20.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ubiquerg=0.8.0
  - umap-learn=0.5.9.post2
  - unicodedata2=16.0.0
  - uritemplate=4.2.0
  - urllib3=2.5.0
  - vcflib=1.0.12
  - vcftools=0.1.17
  - veracitools=0.1.3
  - wayland=1.24.0
  - wcwidth=0.2.14
  - wget=1.21.4
  - wheel=0.45.1
  - wrapt=2.0.0
  - x265=3.5
  - xkeyboard-config=2.46
  - xmltodict=1.0.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.22.0
  - yq=3.4.3
  - yte=1.8.1
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
prefix: /home/adminabgsc/miniconda3/envs/population_var_calling
